addr = "localhost"
port = 1965
cert = "./demo/cert.pem"
key = "./demo/key.pem"
root = "./demo/capsule"
trace = "stderr"
level = "info"

footer = """

~~~~~~~~~可上九天揽月，可下五洋捉鳖，谈笑凯歌还。~~~~~~~~~
served by https://github.com/trislu/zhuque

"""
badge = """
                                                                    
                                 :#                                 
                                =*.                                 
                        :-==*=-:   .=-:=*=                          
                       -=. .+=    =.-:::-*:***+:                    
              .=-..:=+=#-   .    :-+     =+==-:-:                   
            .:-*=+*++#*#*+:      ::+    .==:    :-++-               
               :==+*######*..     .#=    :#:   .+  .*.  ...         
                      :*###-==      :*=  .=#.  := .:=*####.         
                       .##*  . .=++=.=+++##########***##=.          
                     :*+=#.   :#-*: :.:#*:....:-+**===*:.=#=        
      .          .-*-==#:    :#-=: :: -= :-::=. ::=++-:*##+:.       
    =*         :*+#+==+      +==#-.*::#:=: ..:::::=:  :##-          
    *=.      =## *:*+:-=    .#.+.:=::-:#+:::::.:=: ++ -##+          
    :+====+==#*+:==#: :+##: =::#######-=*=:-++**::- +-.*#= .::      
            -#**=::=:      =.:#########:.. :##: = =-.* +#=:+::#:    
   =.     .+*#*=.+-**.   :+:.+#########+.:.+:    ::+ *:+#:=-*:      
  .*=:::=*==-#**=:.::+*#*:=-::#########:.=-     --.*:#:##::+:       
    -++*+:. .*##=*..:*--=:#+.:.=*#####:==      .=.=.-::#-::-        
           .=:*###+=..-=--+..*#== :=:-:      .:=-*:---#-:::         
    .*:  .-:=. =###*:== :=.==:#:*..=*-:::=.:*#+#*:=.=*::-:          
     =:::-*:    .==-**=*+::*#==+:=-:=..:..::.-###-##*==:            
        .         .==*+::=+=:*.#+ .-..=.-.*:::+#########+:.         
          ::=+=:     -*##*##*=#+.: :#..+*++. -#:..... ..=##:        
       :-:*++=-=#**=.   .-=**#*==#=-+*-+**=+#+:..::==-   *#.        
                .*..+#*:. :=:..+###.         =*::  .-=.:#+.         
                 ==   .:*####=  :==#           +=  =#=              
                          .=*:   -*           =#=:==:               
                                 --       .==*:                     
                                 *                                  
                                +.                                  
                       .=#=    -#                                   
                      :=+=:==-+#**:--:.                             
                       ::  .::        -+                            
"""
